/** @type {import('next').NextConfig} */
const nextConfig = {
  // 1. YOUR EXISTING IMAGE CONFIG
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**', // Allows all external images
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',  
      },
      {
        protocol: 'https',
        hostname: 'cdn.pixabay.com',
      },
    ],
  },

  // 2. PHASE 2: REDIRECTS (The "Traffic Rescuers")
  async redirects() {
    return [
      // --- COMMON WORDPRESS REDIRECTS ---
      
      // Case A: Old Category Pages (e.g., /product-category/gaming-pcs)
      // We send them to your new generic "/products" page
      {
        source: '/product-category/:slug*', 
        destination: '/products', 
        permanent: true, // 301 Redirect (Tells Google "We moved here forever")
      },

      // Case B: Old "Shop" Landing Page
      {
        source: '/shop',
        destination: '/products',
        permanent: true,
      },

      // Case C: Old Tag Pages (often generated by WP)
      {
        source: '/product-tag/:slug*',
        destination: '/products',
        permanent: true,
      },

      // Case D: The "Ghost" WP Admin (Security Best Practice)
      // If bots try to find your WordPress login, send them home
      {
        source: '/wp-admin',
        destination: '/',
        permanent: false,
      },

      // --- SPECIFIC HIGH-TRAFFIC PAGES (OPTIONAL) ---
      // If you had a specific viral product, map it manually here:
      // {
      //   source: '/product/old-rtx-4090-build',
      //   destination: '/product/NEW-UUID-FROM-SUPABASE',
      //   permanent: true,
      // },
    ];
  },
};

export default nextConfig;